# Generated by Django 5.1.7 on 2025-04-06 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hatch_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="message_file",
            field=models.TextField(blank=True, null=True),
        ),
    ]
