# Generated by Django 5.1.7 on 2025-04-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hatch_app', '0002_message_message_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket',
            name='picture',
            field=models.CharField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSpwxCN33LtdMLbWdhafc4HxabqpaU0qVbDxQ&s', max_length=255),
        ),
        migrations.AddField(
            model_name='channel',
            name='picture',
            field=models.CharField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSpwxCN33LtdMLbWdhafc4HxabqpaU0qVbDxQ&s', max_length=255),
        ),
    ]
