# Generated by Django 5.1.7 on 2025-04-08 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hatch_app', '0003_bucket_picture_channel_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucketmember',
            name='invite_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='channelmember',
            name='invite_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
