# Generated by Django 5.1.7 on 2025-04-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hatch_app", "0004_bucketmember_invite_accepted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="join_channel",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
