# Generated by Django 5.1.7 on 2025-04-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hatch_app", "0005_message_join_channel"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="uploads/")),
                ("file_name", models.CharField(max_length=255)),
                ("file_type", models.CharField(max_length=100)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("bucket", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
