# Generated by Django 5.1.7 on 2025-04-24 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hatch_app', '0006_remove_task_channel_remove_task_parent_task_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hatch_app.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hatch_app.user')),
            ],
        ),
    ]
