# Generated by Django 5.1.7 on 2025-04-25 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hatch_app', '0006_uploadedfile'),
        ('hatch_app', '0007_notification'),
    ]

    operations = [
    ]
