# Generated by Django 5.1.7 on 2025-04-25 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hatch_app', '0008_merge_0006_uploadedfile_0007_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='bucket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='hatch_app.bucket'),
        ),
        migrations.AlterField(
            model_name='channelmember',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='hatch_app.channel'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hatch_app.task'),
        ),
    ]
